#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
target ‘Test’ do

use_frameworks!
pod 'grabData'




end

